# app/Resources/config/routing.yml

ticketing_home:
    path:     /ticketing
    defaults:
        _controller: TicketingBundle:Booking:index

ticketing_details:
    path:      /details
    defaults:
        _controller: TicketingBundle:Booking:details

ticketing_confirmation:
    path:      /confirmation
    defaults:
        _controller: TicketingBundle:Booking:confirmation

ticketing_payment:
    path:      /payment
    defaults:
        _controller: TicketingBundle:Booking:payment

ticketing_summary:
    path:      /summary
    defaults:
        _controller: TicketingBundle:Booking:summary